name: example
description: A simple command-line application.
version: 1.0.0

publish_to: none

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  sentry:
    path: ../../dart

dev_dependencies:
  lints: ^3.0.0
