name: sentry_dart_web_example
description: An absolute bare-bones web app.

publish_to: 'none'

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  sentry:
    path: ../../dart

dev_dependencies:
  build_runner: ^2.4.8
  build_web_compilers: ^4.0.9
  lints: ^3.0.0
  webdev: ^3.4.0
